import type { Listing, BoostFundStats, ChatMessage } from "@/lib/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "1",
    title: "18K Gold Cuban Link Chain — 120g",
    description: "Authenticated 18K solid gold Cuban link, 22 inches, Brink's insured vault custody.",
    category: "chain",
    images: ["/listings/chain-1.jpg"],
    video360Url: "/listings/chain-1-360.mp4",
    startPrice: 8500,
    targetPrice: 12000,
    hiddenReserve: 9500,
    currentBid: 10200,
    bidCount: 47,
    auctionType: "live",
    status: "live",
    sellerId: "seller-1",
    sellerName: "GoldVault_NYC",
    trustBadges: ["bling-verified", "gia-certified", "brinks-insured", "money-back"],
    certNumber: "GIA-2847193",
    isLive: true,
    viewerCount: 342,
  },
  {
    id: "2",
    title: "Rolex Submariner Date — 41mm Black Dial",
    description: "2023 Rolex Submariner with box, papers, and GIA-verified authenticity.",
    category: "watch",
    images: ["/listings/rolex-1.jpg"],
    startPrice: 12000,
    targetPrice: 15500,
    currentBid: 13800,
    bidCount: 31,
    auctionType: "live",
    status: "live",
    sellerId: "seller-2",
    sellerName: "LuxTime_Collective",
    trustBadges: ["bling-verified", "gia-certified", "money-back"],
    certNumber: "AGS-W-99201",
    isLive: true,
    viewerCount: 218,
  },
  {
    id: "3",
    title: "2.5ct Round Brilliant Diamond — VS1, G Color",
    description: "GIA-certified loose diamond, excellent cut, ideal for custom setting.",
    category: "diamond",
    images: ["/listings/diamond-1.jpg"],
    startPrice: 18000,
    targetPrice: 24000,
    hiddenReserve: 20000,
    currentBid: 21500,
    bidCount: 19,
    auctionType: "timed",
    status: "live",
    sellerId: "seller-3",
    sellerName: "DiamondDirect",
    trustBadges: ["bling-verified", "gia-certified", "brinks-insured", "money-back"],
    certNumber: "GIA-2145988776",
    endsAt: new Date(Date.now() + 86400000 * 2).toISOString(),
    isLive: false,
  },
  {
    id: "4",
    title: "1oz PAMP Suisse Gold Bar — Sealed",
    description: "Sealed 1oz PAMP Suisse gold bar with assay certificate.",
    category: "gold-bar",
    images: ["/listings/gold-bar-1.jpg"],
    startPrice: 2200,
    targetPrice: 2800,
    currentBid: 2450,
    bidCount: 12,
    auctionType: "timed",
    status: "live",
    sellerId: "seller-4",
    sellerName: "BullionBay",
    trustBadges: ["bling-verified", "brinks-insured", "money-back"],
    endsAt: new Date(Date.now() + 86400000).toISOString(),
    isLive: false,
  },
];

export const MOCK_BOOST_FUND: BoostFundStats = {
  totalCollected: 284750,
  totalDistributed: 198420,
  featuredSlotsSubsidized: 1247,
  mysteryPrizesAwarded: 89,
  lastVaultProofUrl: "https://blingbids.com/vault-proof/2026-06",
  lastVaultProofDate: "2026-06-01",
};

export const MOCK_CHAT: ChatMessage[] = [
  { id: "1", userId: "u1", userName: "CryptoKing", message: "🔥🔥🔥", type: "emoji-storm", timestamp: new Date().toISOString() },
  { id: "2", userId: "u2", userName: "GoldHunter", message: "Bid $10,500!", type: "bid", timestamp: new Date().toISOString() },
  { id: "3", userId: "u3", userName: "BlingFan", message: "That chain is INSANE", type: "message", timestamp: new Date().toISOString() },
  { id: "4", userId: "system", userName: "Blingbids", message: "New high bid: $10,200", type: "system", timestamp: new Date().toISOString() },
];